name: Tag Deployment (Staging)
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    tags:
      - "staging/*"
jobs:
  Deploy-Staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --git-branch=staging --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: vercel-deploy
        run: echo "DEPLOYMENT_URL_VERCEL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> "$GITHUB_OUTPUT"

      - name: Assign Staging Domain to Deployment
        run: vercel alias set ${{ steps.vercel-deploy.outputs.DEPLOYMENT_URL_VERCEL }} ${{ vars.DEPLOYMENT_URL_STAGING }} --token=${{ secrets.VERCEL_TOKEN }} --scope svt-robotics
